### ISSUE TITLE
Grafiken

### ISSUE THREAD

**Issue by dschmidl** [dschmidl/Forschungsseminar#11]
Folgende Grafiken werden benötigt:
- Defaultbild für Navigationssystem: Soll nur den derzeitigen Standort (und Umgebung) anzeigen, also vor der Auswahl der Zieladresse
- Bild mit Route: Soll Route zum Ziel anzeigen
- "Route wird berechnet"-Bild

**Comment by beLuxe06** [comment]
Hab mal 3 Sketches erstellt. Können jederzeit noch geändert werden. (Farbe, Kartenausschnitt, Route, Icons alles einzeln änderbar)

**Comment by beLuxe06** [comment]
Achja Dateien sind im Drive Ordner unter "Design-Sketches"

**Comment by dschmidl** [comment]
Bitte hier in Github in den Ornder "Grafiken" laden. Danke
